### PR TITLE
fixes Error analysis import

### PR DESCRIPTION
**Pull request by wivern**
Fixes OHDSI/ArachneCentralAPI#624

### CODE REVIEW

**Comment by pavgra** [comment]
Now I have following exception at Central:

```
2019-08-22 14:05:00.434 ERROR 20172 --- [nio-8080-exec-7] .o.a.p.a.v.c.ExceptionHandlingController : error save file to disk, filename=77c03974-6867-484c-a1d0-078983ecfd7c ex=java.nio.file.InvalidPathException: Illegal char <:> at index 8: Sisyphus:  incidence of fractures all time post-exposure to alendronate and raloxefine_99321_target.sql

java.io.IOException: error save file to disk, filename=77c03974-6867-484c-a1d0-078983ecfd7c ex=java.nio.file.InvalidPathException: Illegal char <:> at index 8: Sisyphus:  incidence of fractures all time post-exposure to alendronate and raloxefine_99321_target.sql
	at com.odysseusinc.arachne.portal.service.analysis.impl.BaseAnalysisServiceImpl.saveFile(BaseAnalysisServiceImpl.java:463) ~[classes/:na]
```

**Comment by wivern** [comment]
@pavgra Good catch, now the quality assurance of month title goes to you.
Seems like we never have protection against illegal characters inside filename before.

**Comment by wivern** [comment]
@pavgra issue isn't reproducible on my environment, could you provide steps to reproduce?
I've tried to add some filename illegal characters to analysis name but with no success:

test ir _ Vitaly's new study2 _ Arachne

**Comment by pavgra** [comment]
I assume this is Windows specific issue because you can use `:` in Unix file names but cannot in Windows:
```
2019-08-23 09:29:07.319 ERROR 5624 --- [nio-8080-exec-6] c.o.a.p.s.a.i.BaseAnalysisServiceImpl    : error save file to disk, filename=c6757589-ddf5-4353-9f30-0e0ce4c8f018 ex=java.nio.file.InvalidPathException: Illegal char <:> at index 8: Sisyphus:  incidence of fractures all time post-exposure to alendronate and raloxefine_99321_target.sql

java.nio.file.InvalidPathException: Illegal char <:> at index 8: Sisyphus:  incidence of fractures all time post-exposure to alendronate and raloxefine_99321_target.sql
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:1.8.0_171]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:1.8.0_171]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:1.8.0_171]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[na:1.8.0_171]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[na:1.8.0_171]
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53) ~[na:1.8.0_171]
	at com.odysseusinc.arachne.portal.service.impl.AnalysisPreprocessorService.preprocessFile(AnalysisPreprocessorService.java:55) ~[classes/:na]
	at com.odysseusinc.arachne.portal.service.analysis.impl.BaseAnalysisServiceImpl.saveFile(BaseAnalysisServiceImpl.java:456) [classes/:na]
	at com.odysseusinc.arachne.portalenterprise.service.analysis.impl.EnterpriseAnalysisServiceImpl.saveFile(EnterpriseAnalysisServiceImpl.java:219) [classes/:na]
	at com.odysseusinc.arachne.portalenterprise.service.analysis.impl.EnterpriseAnalysisServiceImpl.saveFile(EnterpriseAnalysisServiceImpl.java:100) [classes/:na]
	at com.odysseusinc.arachne.portal.service.analysis.impl.BaseAnalysisServiceImpl.saveFiles(BaseAnalysisServiceImpl.java:408) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
```

**Pull request merged**
